name: Check Widgets Available

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
    # 只在 commit message 包含 [metadata] 时触发
    tags:
      - '*[metadata]*'

permissions:
  contents: write  # 允许 GitHub Actions 访问 Releases API

jobs:
  check-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装依赖
        run: cd script && npm install

      - name: 运行 ZIP 检测
        run: cd script && node check.js
      
      - name: Generate Tag Name
        id: generate_tag
        run: |
          # 获取当前日期
          DATE=$(date +'%Y.%m.%d')
          # 获取最新提交的数量
          COMMIT_COUNT=$(git rev-list --count HEAD)
          # 合成标签名
          TAG_NAME="rel_${DATE}.${COMMIT_COUNT}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "release-placeholder"  # 使用虚拟标签名
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            script/metadata.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
